/** LAYOUT */
export const LAYOUT_MEDIA_QUERY_TABLET_NUMBER = 768
export const LAYOUT_MEDIA_QUERY_TABLET = `${LAYOUT_MEDIA_QUERY_TABLET_NUMBER}px`

/** CONTENT HOLDER */
export const CONTENTHOLDER_PADDING = "16px"

/** NAVIGATION */
export const NAVIGATION_PADDING = "16px"

/** BLOG POST LIST */
export const BLOGPOSTLISTHOLDER_MARGIN = "8px 0"

export const BLOGPOSTLISTLINK_MARGIN = "4px 0"
